# Generated by Django 4.2 on 2024-10-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjualan', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='penjualan',
            name='is_close',
            field=models.BooleanField(default=False),
        ),
    ]
