# Generated by Django 4.2 on 2024-10-22 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('update_on', models.DateTimeField(auto_now=True)),
                ('nama_barang', models.CharField(max_length=100)),
                ('deskripsi', models.CharField(blank=True, max_length=100)),
                ('barcode', models.CharField(blank=True, max_length=36)),
                ('stok', models.PositiveSmallIntegerField(default=0)),
                ('harga', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
